# Test against these versions of Node.js
environment:
  matrix:
    # Node versions to run
    - nodejs_version: 6

# Install scripts--runs after repo cloning
install:
  # Install the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts
test_script:
  # Output debugging info
  - node --version
  - npm --version
  # run tests
  - npm run test

# Don't actually build
build: off
